package org.lawrencebower.docgen.web_logic.business.mapping.auto_mapped;

public enum AutoMappedField {

    DATE("DATE"),
    BUSINESS_ADDRESS("AUTO_MAPPED_BUSINESS_ADDRESS"),
    BUSINESS_CONTACT_NAME("AUTO_MAPPED_BUSINESS_CONTACT_NAME"),
    BUSINESS_COUNTRY("AUTO_MAPPED_BUSINESS_COUNTRY"),
    BUSINESS_NAME("AUTO_MAPPED_BUSINESS_NAME"),
    BUSINESS_NAME_AND_ADDRESS("AUTO_MAPPED_BUSINESS_NAME_AND_ADDRESS"),
    BUSINESS_PHONE("AUTO_MAPPED_BUSINESS_PHONE"),
    CUSTOMER_ADDRESS("AUTO_MAPPED_CUSTOMER_ADDRESS"),
    CUSTOMER_CONTACT_NAME("AUTO_MAPPED_CUSTOMER_CONTACT_NAME"),
    CUSTOMER_COUNTRY("AUTO_MAPPED_CUSTOMER_COUNTRY"),
    CUSTOMER_NAME("AUTO_MAPPED_CUSTOMER_NAME"),
    CUSTOMER_NAME_AND_ADDRESS("AUTO_MAPPED_CUSTOMER_NAME_AND_ADDRESS"),
    CUSTOMER_PHONE("AUTO_MAPPED_CUSTOMER_PHONE"),
    VENDOR_ADDRESS("AUTO_MAPPED_VENDOR_ADDRESS"),
    VENDOR_CONTACT_NAME("AUTO_MAPPED_VENDOR_CONTACT_NAME"),
    VENDOR_COUNTRY("AUTO_MAPPED_VENDOR_COUNTRY"),
    VENDOR_EMAIL("AUTO_MAPPED_VENDOR_EMAIL"),
    VENDOR_NAME("AUTO_MAPPED_VENDOR_NAME"),
    VENDOR_PHONE("AUTO_MAPPED_VENDOR_PHONE"),
    VENDOR_TAX_ID("AUTO_MAPPED_VENDOR_TAX_ID"),
    VENDOR_NAME_AND_ADDRESS("AUTO_MAPPED_VENDOR_NAME_AND_ADDRESS");

    private String name;

    AutoMappedField(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
